sonar.projectKey=boggybumblebee_unifi-protect-archive
sonar.organization=boggybumblebee
sonar.projectName=UniFi Protect Archive
sonar.sources=src
sonar.rust.lcov.reportPaths=lcov.info
sonar.coverage.exclusions=src/main.rs
